### ISSUE TITLE
Usage example for the uploaded callback

### ISSUE THREAD

**Issue by sadortun** [InCuca/ic-firebase-uploader#2]
Hi!

I can see that you `this.$emit('uploaded')`, can you add an attribute to the tag to perform a callback ? Or add an example in the readme on how to catch this event ?

Thanks,
Samuel

**Comment by klarkc** [comment]
Hey, there are examples in the source code (I have to put this online somewhere), just run `npm run serve` on terminal.

**Comment by sadortun** [comment]
Yep, I did found them a little too late !!

**Comment by klarkc** [comment]
Hey I will keep this open to push the docs online sometime :rofl:

**Comment by klarkc** [comment]
Link: https://bit.dev/incuca/incuca-ui/ic-firebase-uploader?example=5d979ff9272ef1001334fb5b
