### ISSUE TITLE
run after upload successful

### ISSUE THREAD

**Issue by devJoshLopez** [InCuca/ic-firebase-uploader#3]
hey im pretty new to vue. i got ic-firebase-uploader to work in my project but now im trying to figure out how to run a function after doUpload() is successful. Any advice? Thank you

**Comment by klarkc** [comment]
there is "uploaded" event that is fired after successful doUpload

https://github.com/InCuca/ic-firebase-uploader/blob/4849224079a7297e06dc163456f0360519005940/src/ic-firebase-uploader/ic-firebase-uploader.vue#L200

and "error" event that is fired if doUpload fails:

https://github.com/InCuca/ic-firebase-uploader/blob/4849224079a7297e06dc163456f0360519005940/src/ic-firebase-uploader/ic-firebase-uploader.vue#L207

example: https://github.com/InCuca/ic-firebase-uploader/blob/master/docs/Database%20Integration.md

**Comment by devJoshLopez** [comment]
Yes! You are amazing. Thank you so much!
